apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis_svc.name  }}
spec:
  selector:
    app: {{ .Values.redis_svc.selector.app  }}
  ports:
    - name: redis
      protocol: TCP
      port: {{ .Values.redis_svc.port }}
