# A simple example of ClusterConfig object with two nodegroups:
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: openstudio-server
  region: us-east-1
  version: "1.29"

vpc:
  cidr: 192.168.0.0/16
  autoAllocateIPv6: true
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: ebs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      ebsCSIController: true

managedNodeGroups:
  - name: web-node-group
    instanceType: m7i.8xlarge
    minSize: 0
    maxSize: 2
    desiredCapacity: 1
    labels:
      nodegroup: web-group
    privateNetworking: true
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        ebs: true
    ssh:
      allow: true
      # Update publicKeyPath for your public key
      publicKeyPath: ~/.ssh/id_rsa.pub
    availabilityZones: ["us-east-1a"]
    volumeSize: 550
    volumeType: gp3

  - name: worker-node-group-spot
    instanceTypes: ["c5.metal", "c5a.24xlarge", "c5ad.24xlarge", "c5d.metal",
    "c6a.24xlarge", "c6i.24xlarge", "c6id.24xlarge", "c6in.24xlarge",
    "c7a.24xlarge", "c7i.24xlarge", "c7i.metal-24xl", "inf1.24xlarge"]
    minSize: 0
    maxSize: 50
    desiredCapacity: 1
    labels:
      nodegroup: worker-group
    privateNetworking: true
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        ebs: true
    spot: true
    ssh:
      allow: true
      # Update publicKeyPath for your public key
      publicKeyPath: ~/.ssh/id_rsa.pub
    availabilityZones: ["us-east-1b"]
    volumeSize: 400
    volumeType: gp3

addons:
  - name: aws-ebs-csi-driver
    wellKnownPolicies:      # add IAM and service account
      ebsCSIController: true