apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web_svc.name   }}
spec:
  selector:
    label: {{ .Values.web_svc.label   }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.web_svc.ports.http   }}
    - name: https
      protocol: TCP
      port:  {{ .Values.web_svc.ports.https   }}


