{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openstudio-server.serviceAccountName" . }}
  labels:
{{ include "openstudio-server.labels" . | nindent 4 }}
{{- end -}}
