apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.db.name }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        label: {{ .Values.db.name }}
    spec:
      containers:
        - name: {{ .Values.db.container.name }}
          image: {{ .Values.db.container.image }}
          ports:
            - containerPort:  {{ .Values.db.container.ports.db_port }}
          volumeMounts:
            - mountPath: /data/db
              name: {{ .Values.db.name }}
      volumes:
        - name: {{ .Values.db.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.db.name }}

