apiVersion: batch/v1
kind: Job
metadata:
  name: nfs-client-cleanup
  namespace: default
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: nfs-client-cleanup
    spec:
      containers:
        - name: kubectl
          image: "k8s.gcr.io/hyperkube:v1.12.1"
          securityContext:
            privileged: true
          imagePullPolicy: "IfNotPresent"
          command:
          - /bin/sh
          - -c
          - >
              kubectl delete deployment web;
              kubectl delete deployment web-background;
              kubectl delete deployment rserve;
              sleep 60;
      restartPolicy: Never
