apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rserve_svc.name  }}
spec:
  selector:
    app: {{ .Values.db.label  }}
    release: {{ .Release.Name }}
  ports:
    - name: rserve
      protocol: TCP
      port: {{ .Values.rserve_svc.port  }}


