apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rserve_svc.name  }}
spec:
  selector:
    label: {{ .Values.rserve_svc.label  }}
  ports:
    - name: rserve
      protocol: TCP
      port: {{ .Values.rserve_svc.port  }}


