apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd
{{ if eq .Values.provider.name "aws" }}
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
{{ end }}
{{ if eq .Values.provider.name "google" }}
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
{{ end }}
reclaimPolicy: Delete
mountOptions:
  - debug
volumeBindingMode: Immediate
