apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd
{{- if eq .Values.provider.name "aws" }}
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
{{- else if eq .Values.provider.name "google" }}
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
{{- else if eq .Values.provider.name "azure" }}
provisioner: kubernetes.io/azure-disk
parameters:
  kind: Managed
  storageaccounttype: StandardSSD_LRS
{{- else }}
provisioner: rancher.io/local-path
parameters:
  nodePath: /data/ssd
  pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}"
{{- end }}
reclaimPolicy: Delete
mountOptions:
  - debug
volumeBindingMode: Immediate
allowedTopologies:
- matchLabelExpressions:
  - key: nodegroup
    values:
      - web-group
