apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd
{{- if eq .Values.provider.name "aws" }}
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
volumeBindingMode: Immediate
{{- else if eq .Values.provider.name "google" }}
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
volumeBindingMode: Immediate
{{- else if eq .Values.provider.name "azure" }}
provisioner: kubernetes.io/azure-disk
parameters:
  kind: Managed
  storageaccounttype: StandardSSD_LRS
volumeBindingMode: Immediate
{{- else }}
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
{{- end }}
reclaimPolicy: Delete
mountOptions:
  - debug
allowedTopologies:
- matchLabelExpressions:
  - key: nodegroup
    values:
      - web-group
