apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        label: db
    spec:
      containers:
        - name: mongo-db
          image: mongo:3.4.10
          ports:
            - containerPort: 27017
