apiVersion: v1
kind: Service
metadata:
  name: ingress-load-balancer
  namespace: default
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    label: web
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443

