apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  storageClassName: standard
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    name: nfs-pvc
    namespace: default
  nfs:
    server: 10.100.227.141
    path: /
