kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc-physical
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 50Gi
