apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  namespace: default
spec:
  clusterIP: 10.100.227.141
  selector:
    role: nfs-server
  ports:
    - name: nfs
      protocol: TCP
      port: 2049
    - name: mountd
      protocol: TCP
      port: 20048
    - name: rpcbind
      protocol: TCP
      port: 111
