apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  claimRef:
    name: nfs-pvc
    namespace: ${NAMESPACE}
  nfs:
    server: ${NFS_ADDR}
    path: /
