apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
        - name: nfs-server
          image: gcr.io/google_containers/volume-nfs
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /exports
              name: nfs-pvc-physical
            - name: nfs-conf-volume
              mountPath: /etc/exports
              subPath: exports
      volumes:
        - name: nfs-pvc-physical 
          persistentVolumeClaim:
            claimName: nfs-pvc-physical 
        - name: nfs-conf-volume
          configMap:
            name: nfs
