apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:4.0.6
          resources:
            requests:
              cpu: 0.5
              memory: 1Gi
          ports:
            - containerPort: 6379
