apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rserve
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        label: rserve
    spec:
      containers:
        - name: rserve
          image: nrel/openstudio-rserve:latest
          resources:
            requests:
              cpu: 3
              memory: 10Gi
          volumeMounts:
            - name: osdata
              mountPath: "/mnt/openstudio"
      volumes:
        - name: osdata
          persistentVolumeClaim:
            claimName: nfs-pvc
