apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        label: web
    spec:
      containers:
        - name: web
          image: nrel/openstudio-server:latest
          resources:
            requests:
              cpu: 1
              memory: 3Gi
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: osdata
              mountPath: "/mnt/openstudio"
          env:
            - name: OS_SERVER_NUMBER_OF_WORKERS
              value: ${OS_SERVER_NUMBER_OF_WORKERS}
            - name: QUEUES
              value: analysis_wrappers
          command: ["bash", "-c", "/usr/local/bin/rails-entrypoint && /usr/local/bin/start-server"]
      volumes:
        - name: osdata
          persistentVolumeClaim:
            claimName: nfs-pvc
