apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ .Values.nfs_rc.name  }}
spec:
  replicas: 1
  selector:
    role: {{ .Values.nfs_rc.selector.role  }}
  template:
    metadata:
      labels:
        role: {{ .Values.nfs_rc.selector.role  }}
    spec:
      containers:
        - name: {{ .Values.nfs_rc.container.name  }}
          image: {{ .Values.nfs_rc.container.image  }}
          ports:
            - name: nfs
              containerPort:  {{ .Values.nfs_rc.container.ports.nfs  }}
            - name: mountd
              containerPort: {{ .Values.nfs_rc.container.ports.mountd  }}
            - name: rpcbind
              containerPort: {{ .Values.nfs_rc.container.ports.rpcbind  }}
          securityContext:
            privileged: {{ .Values.nfs_rc.container.securityContext.privileged  }}
          volumeMounts:
            - mountPath: /exports
              name: nfs-pvc-physical
            - name: nfs-conf-volume
              mountPath: /etc/exports
              subPath: exports
      volumes:
        - name: nfs-pvc-physical 
          persistentVolumeClaim:
            claimName: nfs-pvc-physical 
        - name: nfs-conf-volume
          configMap:
            name: nfs
