kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.nfs_pvc.name  }}
spec:
  accessModes:
    {{ .Values.nfs_pvc.accessModes }}
  storageClassName: "nfs"
  resources:
    requests:
      storage:  {{ .Values.nfs_pvc.storage }}